spring:
  application:
    name: UniTakeoutServer

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_takeout?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

# MyBatis 配置
mybatis:
  # mapper.xml 文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.nbufe.zfr.UniTakeout_server.entity
  configuration:
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 开启缓存
    cache-enabled: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 延迟加载
    lazy-loading-enabled: true
    # 一级缓存范围
    local-cache-scope: session

# 服务器配置
server:
  port: 3000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

unitakeout:
  alioss:
    endpoint: ${UNITAKEOUT_OSS_ENDPOINT}
    access-key-id: ${UNITAKEOUT_OSS_ACCESS_KEY_ID}
    access-key-secret: ${UNITAKEOUT_OSS_ACCESS_KEY_SECRET}
    bucket-name: ${UNITAKEOUT_OSS_BUCKET_NAME}
